### ISSUE TITLE
How to train this on DIOR dataset?

### ISSUE THREAD

**Issue by Warriors-go** [Horatio9702/BUAA_PALoss#2]
Thanks for your great work. I wanna train this work on DIOR dataset, could you please give me some suggestions about how to modify the code?

**Comment by Horatio9702** [comment]
Hi, you can follow https://github.com/luiszeni/Boosted-OICR

**Comment by Warriors-go** [comment]
2c83b6af#ㄋⅱっ＿ㄍ＿ㄍ

**Comment by Warriors-go** [comment]
Thanks, I will try it.
